cgu:
    path: /cgu
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: cgu.html.twig
mentions_legales:
    path: /mentions_legales
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: mentions_legales.html.twig
plan_du_site:
    path: /plan_du_site
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: plan_du_site.html.twig
